name       : fossil
version    : 2.22
release    : 11
source     :
    - https://fossil-scm.org/home/tarball/66ee0beb9b47d827bde533fe6a1fb2ead4ceb1936468881b4fb621bd6bdfd862/fossil-src-2.22.tar.gz : b90c40beb75308b0eba46b5add6e54a7a9e65ac90ce86ec8d78ae2a4bb8bae60
license    : BSD-2-Clause
component  : system.utils
summary    : A simple, high-reliability, distributed software configuration management system
description: |
    Fossil is a simple, high-reliability, distributed software configuration management system with
    some features.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-internal-sqlite \
               --disable-static \
               --json
build      : |
    %make
install    : |
    %make_install
