name       : fossil
version    : '2.2'
release    : 2
source     :
    - http://www.fossil-scm.org/index.html/uv/fossil-src-2.2.tar.gz : 9b8f82196eb89e4a2e82b4bcc51e314ae509a22c37073a18a0b325f11c53cf71
license    : BSD-2-Clause
component  : system.utils
summary    : A simple, high-reliability, distributed software configuration management system
description: |
    Fossil is a simple, high-reliability, distributed software configuration management system with
    some features.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-internal-sqlite --json
build      : |
    %make
install    : |
    %make_install
