name       : fossil
version    : 2.11.1
release    : 8
source     :
    - https://www.fossil-scm.org/index.html/tarball/307d94c5/Fossil-307d94c5.tar.gz : 44d297e6da147541afb67e3206878edab24f843e151a1d1ce85db24ed085ced1
license    : BSD-2-Clause
component  : system.utils
summary    : A simple, high-reliability, distributed software configuration management system
description: |
    Fossil is a simple, high-reliability, distributed software configuration management system with
    some features.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-internal-sqlite --json
build      : |
    %make
install    : |
    %make_install
