name       : fossil
version    : '2.8'
release    : 5
source     :
    - https://fossil-scm.org/index.html/uv/fossil-src-2.8.tar.gz : 6a32bec73de26ff5cc8bbb0b7b45360f4e4145931fd215ed91414ed190b3715d
license    : BSD-2-Clause
component  : system.utils
summary    : A simple, high-reliability, distributed software configuration management system
description: |
    Fossil is a simple, high-reliability, distributed software configuration management system with
    some features.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-internal-sqlite --json
build      : |
    %make
install    : |
    %make_install
